const int ARRET  = 0x1FE817E;  //arrêt des moteurs
const int ACCELG = 0x1FEE11E;  //bouton VOL+ : accélération moteur gauche
const int FREING = 0x1FE916E;  //bouton VOL- : décélération moteur gauche
const int AVT1   = 0x1FE1CE3;  //bouton HAUT : marche avant
const int ARR1   = 0x1FE02FD;  //bouton BAS  : marche arrière
const int VIREG  = 0x1FEEC13;  //bouton GAUCHE : ralentissement moteur gauche pendant 1s
const int VIRED  = 0x1FE9C63;  //bouton DROITE : ralentissement moteur droit pendant 1s
const int PAGE   = 0x1FEC13E;  //bouton PAGE : marche avant à Vmini pendant 1s puis arret des moteurs
const int HOME   = 0x1FECE31;  //bouton HOME : marche avant à Vmini pendant 0.2s puis arret des moteurs
const int OKOK   = 0x1FEC837;  //bouton OK : arret des moteurs
const int RETOUR = 0x1FEE41B;  //bouton RETOUR : remettre DCG et DCD à DC
const int SOURIS = 0x1FE12ED;  //bouton SOURIS : allumage/extinction led ESP32CAM