const int ARRET  = 0x807F02FD;  //arrêt des moteurs
const int ACCELG = 0x807F18E7;  //bouton VOL+ : accélération moteur gauche
const int FREING = 0x807F08F7;  //bouton VOL- : décélération moteur gauche
const int AVT1   = 0x807F6897;  //bouton HAUT : marche avant
const int ARR1   = 0x807F58A7;  //bouton BAS  : marche arrière
const int VIREG  = 0x807F8A75;  //bouton GAUCHE : ralentissement moteur gauche pendant 1s
const int VIRED  = 0x807F0AF5;  //bouton DROITE : ralentissement moteur droit pendant 1s
const int PAGE   = 0x807F32CD;  //bouton PAGE : marche avant à Vmini pendant 1s puis arret des moteurs
const int HOME   = 0x807F8877;  //bouton HOME : marche avant à Vmini pendant 0.2s puis arret des moteurs
const int OKOK   = 0x807FC837;  //bouton OK : arret des moteurs
const int RETOUR = 0x807F9867;  //bouton RETOUR : remettre DCG et DCD à DC
const int SOURIS = 0x807F00FF;  //bouton SOURIS : allumage/extinction led ESP32CAM