const uint64_t ARRET  = 0x1FE817E;  //arrêt des moteurs
const uint64_t ACCELG = 0x1FEE11E;  //bouton VOL+ : accélération moteur gauche
const uint64_t FREING = 0x1FE916E;  //bouton VOL- : décélération moteur gauche
const uint64_t AVT1   = 0x1FE1CE3;  //bouton HAUT : marche avant
const uint64_t ARR1   = 0x1FE02FD;  //bouton BAS  : marche arrière
const uint64_t VIREG  = 0x1FEEC13;  //bouton GAUCHE : ralentissement moteur gauche pendant 1s
const uint64_t VIRED  = 0x1FE9C63;  //bouton DROITE : ralentissement moteur droit pendant 1s
const uint64_t PAGE   = 0x1FEC13E;  //bouton PAGE : marche avant à Vmini pendant 1s puis arret des moteurs
const uint64_t HOME   = 0x1FECE31;  //bouton HOME : marche avant à Vmini pendant 0.2s puis arret des moteurs
const uint64_t OKOK   = 0x1FEC837;  //bouton OK : arret des moteurs
const uint64_t RETOUR = 0x1FEE41B;  //bouton RETOUR : remettre DCG et DCD à DC
const uint64_t SOURIS = 0x1FE12ED;  //bouton SOURIS : allumage/extinction led ESP32CAM
